## EUTAX configuration file

## API endpoint rate limits
# If a request exceeds the rate limit, a `429` http error will be raised
# Limit examples:
#   2/second
#   5/minute
#   10/hour
#   100/day
#   500/7days
#   2000/year
#   10/hour;100/day;2000/year
rate_limits: {
  "create_job":              "1000/minute",
  "get_job_status":          "1000/minute",
  "get_job_results_json":    "1000/minute",
  "list_jobs":               "1000/minute",
  "get_job_summaries":       "1000/minute",
  "get_job_summary":         "1000/minute",
  "get_reference_databases": "1000/minute",
}

## Logging configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  # Date format for timestamps
  datefmt: "%Y-%m-%d %H:%M:%S"
  # Timezone for timestamps (IANA timezone database name)
  timezone: "Europe/Tallinn"
  # Number of rotated logs to keep (1 file per day)
  backupCount: 200
  # Whether to also log authentication attempts at the DEBUG level
  log_auth_debug: true
  # Whether to include request payloads in logs (may contain sensitive data)
  log_request_payload: false
